### ISSUE TITLE
Suggestion: It is recommended to use a more intuitive way to demonstrate the accuracy advantages of vivo's large models.

### ISSUE THREAD

**Issue by RussellRao** [vivo-ai-lab/BlueLM#1]
As stated in the title.
https://github.com/vivo-ai-lab/BlueLM#7b-%E6%A8%A1%E5%9E%8B%E7%BB%93%E6%9E%9C

**Comment by gcbanana** [comment]
We have modified the benchmark result form. Thanks for your interest.
