### ISSUE TITLE
请教一下，BlueLM-base和BlueLM-chat的区别

### ISSUE THREAD

**Issue by LiuHao-THU** [vivo-ai-lab/BlueLM#14]
0. pre-train - > BlueLM -> SFT -> BlueLM-base -> RLHF -> BlueLM-chat
1. pre-train -> BlueLM-base -> SFT + RLHF - > BlueLM-chat
请问是上面那一个？

**Comment by gcbanana** [comment]
1

**Comment by xealml** [comment]
![image](https://github.com/vivo-ai-lab/BlueLM/assets/12672103/06f48d18-6fcb-4a0a-946d-6e2a3d28a030)
为啥和llama2-chat命名方式不一样啊
